[package]
name = "sevirs"
version = "0.0.1"
edition = "2021"

[lib]
name = "_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.19.0"
numpy = "0.19"
# rand = "0.8.4"
# numpy
# ndarray = "0.15.3"

[features]
extension-module = ["pyo3/extension-module"]
# default = ["mimalloc"]
