[package]
name = "sevirs"
version = "0.1.0"
edition = "2021"

# "cdylib" is necessary to produce a shared library for Python to import from.
[lib]
name = "_lib"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.4"
pyo3 = "0.19.0"
