from typing import Literal
import polars as pl

from .._typing import cast_literal_list

MRMSType = Literal[
    "BREF_1HR_MAX",
    "BrightBandBottomHeight",
    "BrightBandTopHeight",
    "CREF_1HR_MAX",
    "EchoTop_18",
    "EchoTop_30",
    "EchoTop_50",
    "EchoTop_60",
    "FLASH_CREST_MAXSOILSAT",
    "FLASH_CREST_MAXSTREAMFLOW",
    "FLASH_CREST_MAXUNITSTREAMFLOW",
    "FLASH_HP_MAXSTREAMFLOW",
    "FLASH_HP_MAXUNITSTREAMFLOW",
    "FLASH_QPE_ARI01H",
    "FLASH_QPE_ARI03H",
    "FLASH_QPE_ARI06H",
    "FLASH_QPE_ARI12H",
    "FLASH_QPE_ARI24H",
    "FLASH_QPE_ARI30M",
    "FLASH_QPE_ARIMAX",
    "FLASH_QPE_FFG01H",
    "FLASH_QPE_FFG03H",
    "FLASH_QPE_FFG06H",
    "FLASH_QPE_FFGMAX",
    "FLASH_SAC_MAXSOILSAT",
    "FLASH_SAC_MAXSTREAMFLOW",
    "FLASH_SAC_MAXUNITSTREAMFLOW",
    "GaugeInflIndex_01H_Pass1",
    "GaugeInflIndex_01H_Pass2",
    "GaugeInflIndex_03H_Pass1",
    "GaugeInflIndex_03H_Pass2",
    "GaugeInflIndex_06H_Pass1",
    "GaugeInflIndex_06H_Pass2",
    "GaugeInflIndex_12H_Pass1",
    "GaugeInflIndex_12H_Pass2",
    "GaugeInflIndex_24H_Pass1",
    "GaugeInflIndex_24H_Pass2",
    "GaugeInflIndex_48H_Pass1",
    "GaugeInflIndex_48H_Pass2",
    "GaugeInflIndex_72H_Pass1",
    "GaugeInflIndex_72H_Pass2",
    "H50_Above_-20C",
    "H50_Above_0C",
    "H60_Above_-20C",
    "H60_Above_0C",
    "HeightCompositeReflectivity",
    "HeightLowLevelCompositeReflectivity",
    "LVL3_HREET",
    "LVL3_HighResVIL",
    "LayerCompositeReflectivity_ANC",
    "LayerCompositeReflectivity_High",
    "LayerCompositeReflectivity_Low",
    "LayerCompositeReflectivity_Super",
    "LowLevelCompositeReflectivity",
    "MESH",
    "MESH_Max_120min",
    "MESH_Max_1440min",
    "MESH_Max_240min",
    "MESH_Max_30min",
    "MESH_Max_360min",
    "MESH_Max_60min",
    "MergedAzShear_0-2kmAGL",
    "MergedAzShear_3-6kmAGL",
    "MergedBaseReflectivity",
    "MergedBaseReflectivityQC",
    "MergedReflectivityAtLowestAltitude",
    "MergedReflectivityComposite",
    "MergedReflectivityQC",
    "MergedReflectivityQCComposite",
    "MergedReflectivityQComposite",
    "MergedRhoHV",
    "MergedZdr",
    "Model_0degC_Height",
    "Model_SurfaceTemp",
    "Model_WetBulbTemp",
    "MultiSensor_QPE_01H_Pass1",
    "MultiSensor_QPE_01H_Pass2",
    "MultiSensor_QPE_03H_Pass1",
    "MultiSensor_QPE_03H_Pass2",
    "MultiSensor_QPE_06H_Pass1",
    "MultiSensor_QPE_06H_Pass2",
    "MultiSensor_QPE_12H_Pass1",
    "MultiSensor_QPE_12H_Pass2",
    "MultiSensor_QPE_24H_Pass1",
    "MultiSensor_QPE_24H_Pass2",
    "MultiSensor_QPE_48H_Pass1",
    "MultiSensor_QPE_48H_Pass2",
    "MultiSensor_QPE_72H_Pass1",
    "MultiSensor_QPE_72H_Pass2",
    "NLDN_CG_001min_AvgDensity",
    "NLDN_CG_005min_AvgDensity",
    "NLDN_CG_015min_AvgDensity",
    "NLDN_CG_030min_AvgDensity",
    "POSH",
    "PrecipFlag",
    "PrecipRate",
    "RadarAccumulationQualityIndex_01H",
    "RadarAccumulationQualityIndex_03H",
    "RadarAccumulationQualityIndex_06H",
    "RadarAccumulationQualityIndex_12H",
    "RadarAccumulationQualityIndex_24H",
    "RadarAccumulationQualityIndex_48H",
    "RadarAccumulationQualityIndex_72H",
    "RadarOnly_QPE_01H",
    "RadarOnly_QPE_03H",
    "RadarOnly_QPE_06H",
    "RadarOnly_QPE_12H",
    "RadarOnly_QPE_15M",
    "RadarOnly_QPE_24H",
    "RadarOnly_QPE_48H",
    "RadarOnly_QPE_72H",
    "RadarOnly_QPE_Since12Z",
    "RadarQualityIndex",
    "ReflectivityAtLowestAltitude",
    "Reflectivity_-10C",
    "Reflectivity_-15C",
    "Reflectivity_-20C",
    "Reflectivity_-5C",
    "Reflectivity_0C",
    "RotationTrack120min",
    "RotationTrack1440min",
    "RotationTrack240min",
    "RotationTrack30min",
    "RotationTrack360min",
    "RotationTrack60min",
    "RotationTrackML120min",
    "RotationTrackML1440min",
    "RotationTrackML240min",
    "RotationTrackML30min",
    "RotationTrackML360min",
    "RotationTrackML60min",
    "SHI",
    "SeamlessHSR",
    "SeamlessHSRHeight",
    "SyntheticPrecipRateID",
    "VII",
    "VIL",
    "VIL_Density",
    "VIL_Max_120min",
    "VIL_Max_1440min",
    "WarmRainProbability",
]
MRMS_TYPES = (
    BREF_1HR_MAX,
    BRIGHT_BAND_BOTTOM_HEIGHT,
    BRIGHT_BAND_TOP_HEIGHT,
    CREF_1HR_MAX,
    ECHO_TOP_18,
    ECHO_TOP_30,
    ECHO_TOP_50,
    ECHO_TOP_60,
    FLASH_CREST_MAX_SOIL_SAT,
    FLASH_CREST_MAX_STREAM_FLOW,
    FLASH_CREST_MAX_UNITSTREAM_FLOW,
    FLASH_HP_MAXSTREAMFLOW,
    FLASH_HP_MAXUNITSTREAMFLOW,
    FLASH_QPE_ARI01H,
    FLASH_QPE_ARI03H,
    FLASH_QPE_ARI06H,
    FLASH_QPE_ARI12H,
    FLASH_QPE_ARI24H,
    FLASH_QPE_ARI30M,
    FLASH_QPE_ARIMAX,
    FLASH_QPE_FFG01H,
    FLASH_QPE_FFG03H,
    FLASH_QPE_FFG06H,
    FLASH_QPE_FFGMAX,
    FLASH_SAC_MAXSOILSAT,
    FLASH_SAC_MAXSTREAMFLOW,
    FLASH_SAC_MAXUNITSTREAMFLOW,
    GAUGE_INFL_INDEX_01H_PASS1,
    GAUGE_INFL_INDEX_01H_PASS2,
    GAUGE_INFL_INDEX_03H_PASS1,
    GAUGE_INFL_INDEX_03H_PASS2,
    GAUGE_INFL_INDEX_06H_PASS1,
    GAUGE_INFL_INDEX_06H_PASS2,
    GAUGE_INFL_INDEX_12H_PASS1,
    GAUGE_INFL_INDEX_12H_PASS2,
    GAUGE_INFL_INDEX_24H_PASS1,
    GAUGE_INFL_INDEX_24H_PASS2,
    GAUGE_INFL_INDEX_48H_PASS1,
    GAUGE_INFL_INDEX_48H_PASS2,
    GAUGE_INFL_INDEX_72H_PASS1,
    GAUGE_INFL_INDEX_72H_PASS2,
    H50_ABOVE_M20C,
    H50_ABOVE_0C,
    H60_ABOVE_M20C,
    H60_ABOVE_0C,
    HEIGHT_COMPOSITEREFLECTIVITY,
    HEIGHT_LOWLEVELCOMPOSITEREFLECTIVITY,
    LVL3_HR_EET,
    LVL3_HIGH_RES_VIL,
    LAYER_COMPOSITE_REFLECTIVITY_ANC,
    LAYER_COMPOSITE_REFLECTIVITY_HIGH,
    LAYER_COMPOSITE_REFLECTIVITY_LOW,
    LAYER_COMPOSITE_REFLECTIVITY_SUPER,
    LOW_LEVEL_COMPOSITE_REFLECTIVITY,
    MESH,
    MESH_MAX_120MIN,
    MESH_MAX_1440MIN,
    MESH_MAX_240MIN,
    MESH_MAX_30MIN,
    MESH_MAX_360MIN,
    MESH_MAX_60MIN,
    MERGED_AZ_SHEAR_0_2KMAGL,
    MERGED_AZ_SHEAR_3_6KMAGL,
    MERGED_BASE_REFLECTIVITY,
    MERGED_BASE_REFLECTIVITYQC,
    MERGED_REFLECTIVITY_AT_LOWEST_ALTITUDE,
    MERGED_REFLECTIVITY_COMPOSITE,
    MERGED_REFLECTIVITY_QC,
    MERGED_REFLECTIVITY_QC_COMPOSITE,
    MERGED_REFLECTIVITY_QC_COMPOSITE,
    MERGED_RHOHV,
    MERGED_ZDR,
    MODEL_0DEGC_HEIGHT,
    MODEL_SURFACE_TEMP,
    MODEL_WETBULB_TEMP,
    MULTI_SENSOR_QPE_01H_PASS1,
    MULTI_SENSOR_QPE_01H_PASS2,
    MULTI_SENSOR_QPE_03H_PASS1,
    MULTI_SENSOR_QPE_03H_PASS2,
    MULTI_SENSOR_QPE_06H_PASS1,
    MULTI_SENSOR_QPE_06H_PASS2,
    MULTI_SENSOR_QPE_12H_PASS1,
    MULTI_SENSOR_QPE_12H_PASS2,
    MULTI_SENSOR_QPE_24H_PASS1,
    MULTI_SENSOR_QPE_24H_PASS2,
    MULTI_SENSOR_QPE_48H_PASS1,
    MULTI_SENSOR_QPE_48H_PASS2,
    MULTI_SENSOR_QPE_72H_PASS1,
    MULTI_SENSOR_QPE_72H_PASS2,
    NLDN_CG_001MIN_AVG_DENSITY,
    NLDN_CG_005MIN_AVG_DENSITY,
    NLDN_CG_015MIN_AVG_DENSITY,
    NLDN_CG_030MIN_AVG_DENSITY,
    POSH,
    PRECIP_FLAG,
    PRECIP_RATE,
    RADAR_ACCUMULATION_QUALITY_INDEX_01H,
    RADAR_ACCUMULATION_QUALITY_INDEX_03H,
    RADAR_ACCUMULATION_QUALITY_INDEX_06H,
    RADAR_ACCUMULATION_QUALITY_INDEX_12H,
    RADAR_ACCUMULATION_QUALITY_INDEX_24H,
    RADAR_ACCUMULATION_QUALITY_INDEX_48H,
    RADAR_ACCUMULATION_QUALITY_INDEX_72H,
    RADAR_ONLY_QPE_01H,
    RADAR_ONLY_QPE_03H,
    RADAR_ONLY_QPE_06H,
    RADAR_ONLY_QPE_12H,
    RADAR_ONLY_QPE_15M,
    RADAR_ONLY_QPE_24H,
    RADAR_ONLY_QPE_48H,
    RADAR_ONLY_QPE_72H,
    RADAR_ONLY_QPE_SINCE12Z,
    RADAR_QUALITY_INDEX,
    REFLECTIVITY_AT_LOWEST_ALTITUDE,
    REFLECTIVITY_M10C,
    REFLECTIVITY_M15C,
    REFLECTIVITY_M20C,
    REFLECTIVITY_M5C,
    REFLECTIVITY_0C,
    ROTATION_TRACK120MIN,
    ROTATION_TRACK1440MIN,
    ROTATION_TRACK240MIN,
    ROTATION_TRACK30MIN,
    ROTATION_TRACK360MIN,
    ROTATION_TRACK60MIN,
    ROTATION_TRACKML120MIN,
    ROTATION_TRACKML1440MIN,
    ROTATION_TRACKML240MIN,
    ROTATION_TRACKML30MIN,
    ROTATION_TRACKML360MIN,
    ROTATION_TRACKML60MIN,
    SHI,
    SEAMLESS_HSR,
    SEAMLESS_HSR_HEIGHT,
    SYNTHETIC_PRECIP_RATE_ID,
    VII,
    VIL,
    VIL_DENSITY,
    VIL_MAX_120MIN,
    VIL_MAX_1440MIN,
    WARM_RAIN_PROBABILITY,
) = cast_literal_list(list[MRMSType])

# =============================================================================
(GEOMETRY, FEATURES, PROPERTIES) = ("geometry", "features", "properties")
ProbsevereColumn = Literal[
    "ID",
    "validTime",
    "PS",
    "MUCAPE",
    "MLCAPE",
    "MLCIN",
    "EBSHEAR",
    "SRH01KM",
    "MEANWIND_1-3kmAGL",
    "MESH",
    "VIL_DENSITY",
    "FLASH_RATE",
    "FLASH_DENSITY",
    "MAXLLAZ",
    "P98LLAZ",
    "P98MLAZ",
    "MAXRC_EMISS",
    "MAXRC_ICECF",
    "WETBULB_0C_HGT",
    "PWAT",
    "CAPE_M10M30",
    "LJA",
    "SIZE",
    "AVG_BEAM_HGT",
    "MOTION_EAST",
    "MOTION_SOUTH",
    "coordinates",
]

PROBSEVERE_COLUMNS = (
    ID,
    VALID_TIME,
    PS,
    MU_CAPE,
    ML_CAPE,
    ML_CIN,
    EB_SHEAR,
    SRH01KM,
    MEAN_WIND_1_3KM_AGL,
    MESH,
    VIL_DENSITY,
    FLASH_RATE,
    FLASH_DENSITY,
    MAX_LLAZ,
    P98_LLAZ,
    P98_MLAZ,
    MAXRC_EMISS,
    MAXRC_ICECF,
    WET_BULB_0C_HGT,
    PWAT,
    CAPE_M10M30,
    LJA,
    SIZE,
    AVG_BEAM_HGT,
    MOTION_EAST,
    MOTION_SOUTH,
    COORDINATES,
) = cast_literal_list(list[ProbsevereColumn])
# 20210601_000240
PROBSEVERE_DATETIME_FORMAT = "%Y%m%d_%H%M%S UTC"

PROBSEVERE_SCHEMA = {
    MU_CAPE: pl.Int32,
    ML_CAPE: pl.Int32,
    ML_CIN: pl.Int32,
    EB_SHEAR: pl.Float32,
    SRH01KM: pl.Int32,
    MEAN_WIND_1_3KM_AGL: pl.Float32,
    MESH: pl.Float32,
    VIL_DENSITY: pl.Float32,
    FLASH_RATE: pl.Int32,
    FLASH_DENSITY: pl.Float32,
    MAX_LLAZ: pl.Float32,
    P98_LLAZ: pl.Float32,
    P98_MLAZ: pl.Float32,
    MAXRC_EMISS: pl.Utf8,
    MAXRC_ICECF: pl.Utf8,
    WET_BULB_0C_HGT: pl.Float32,
    PWAT: pl.Float32,
    CAPE_M10M30: pl.Int32,
    LJA: pl.Float32,
    SIZE: pl.Int32,
    AVG_BEAM_HGT: pl.Utf8,
    MOTION_EAST: pl.Float32,
    MOTION_SOUTH: pl.Float32,
    PS: pl.Int32,
    ID: pl.Int32,
    VALID_TIME: pl.Datetime,
    COORDINATES: pl.List,
}
